In [1]:
# Python offers its primitive way of working with array
# However its not memory optimized

# The goal of using Numpy for Array creation and working is
# 1. Efficient Memory Management and Optimization
# 2. Faster Read and Write

# Numpy is an external package
# You need to import this package in the program before usage

In [2]:
import numpy as np

In [3]:
# Create a One Dimensional Array
# Using Collection Object

list1 = [1,2,3,4]

oneDimExample = np.array(list1)

oneDimExample

array([1, 2, 3, 4])

In [4]:
type(oneDimExample)

numpy.ndarray

In [5]:
#To check the dimension of the array
oneDimExample.ndim

1

In [6]:
#To check the shape of the array | Find the number of elements in the array

oneDimExample.shape

(4,)

In [7]:
#Create a two dimensional Array

list2 = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]


twoDimExample = np.array(list2)

twoDimExample

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
type(twoDimExample)

numpy.ndarray

In [9]:
twoDimExample.ndim

2

In [10]:
twoDimExample.shape

(3, 3)

In [11]:
#Arithmetic Operations in Arrays
#Every Arithmetic operation in an array performed are ELEMENT-WISE Operation

In [13]:
#Addition

twoDimExample + twoDimExample

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [14]:
#Subtraction
twoDimExample - twoDimExample

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [15]:
#Division
twoDimExample / twoDimExample

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
#Multiplication
twoDimExample * twoDimExample

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [17]:
#In numpy you can create
# a. Array
# b. Matrix

# To create a matrix


matrix1 = np.matrix(twoDimExample)

In [18]:
matrix1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [19]:
matrix1 * matrix1

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [20]:
#Concept of Broadcasting
#

twoDimExample * 3

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [21]:
list3 = [
    [1.111111111,2.22222222],
    [3.3,4.5]
]

arr1 = np.array(list3)

arr1

array([[1.11111111, 2.22222222],
       [3.3       , 4.5       ]])

In [22]:
np.set_printoptions(precision=3)
arr1

array([[1.111, 2.222],
       [3.3  , 4.5  ]])

In [23]:
#Changing Dimensions
# 1D to 2D
# 2D to 1D

In [24]:
data = np.array([1,2,3,4,5,6,7,8,9])

data

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
data.shape

(9,)

In [26]:
#Goal: Represent the above array in 2d
# reshape() ---- This function will help change the dimension of the array
# from 1D to 2D considering the data is compiled successfully.

# Compiled means all data elements present in the array must participate

In [29]:
data.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
data.reshape(4,4)

ValueError: cannot reshape array of size 9 into shape (4,4)

In [34]:
# 2D to 1D

twoDimExample

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
#ravel() ---- flattening the multi-dimensional array

twoDimExample1 = twoDimExample.ravel()

In [38]:
twoDimExample1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
num1 = 10
num2 = 20
num3 = 40

arr2 = np.array([num1,num2,num3])

In [40]:
arr2

array([10, 20, 40])

In [41]:
list1 = [1,2,3,4,7,9,0,5,4,]

oneDimExample = np.array(list1)

oneDimExample

array([1, 2, 3, 4, 7, 9, 0, 5, 4])

In [43]:
oneDimExample = oneDimExample.reshape(3,3)

In [44]:
oneDimExample

array([[1, 2, 3],
       [4, 7, 9],
       [0, 5, 4]])

In [45]:
oneD = oneDimExample.reshape(3,3)

In [47]:
oneD = oneD.ravel()

array([1, 2, 3, 4, 7, 9, 0, 5, 4])

In [48]:
oneD

array([[1, 2, 3],
       [4, 7, 9],
       [0, 5, 4]])