In [1]:
import numpy as np

In [2]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

In [3]:
#Working with 1d array
#Data Extraction --- Similar to syntax of lists

data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
data[6]

7

In [5]:
data[2:6]

array([3, 4, 5, 6])

In [6]:
#Two Dimensional Array

data1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25])
twodarray = data1.reshape(5,5)

In [7]:
twodarray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [8]:
#Extracting single element
twodarray[2,2]

13

In [9]:
#Extract series of elements

twodarray[1:4 , 1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [10]:
twodarray[1:3,1:4]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [ ]:
#Fancy Indexing (Check whiteboard notes for concept)

In [11]:
twodarray[ [1,1,2,2] , [0,2,1,3] ]

array([ 6,  8, 12, 14])

In [12]:
twodarray[ [1,1,2,2] , [0,2,1,3] ].reshape(2,2)

array([[ 6,  8],
       [12, 14]])

In [13]:
twodarray[ [3,1,2,4], [0,1,2,3] ]

array([16,  7, 13, 24])