In [1]:
import numpy as np
data1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25])

In [2]:
data1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [3]:
#Check if the number 11 exists in the given array

11 in data1

True

In [4]:
# Comparison Operatots
# >,<,>=,<=,!=,==

# Logical Operators
# and or not
#
# and ------ &
# or ------- |
# not ------ ~

In [6]:
data1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [5]:
data1 == 11

array([False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [9]:
data1 > 11

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [7]:
data1[ data1 == 11 ]

array([11])

In [8]:
data1[ data1 > 11 ]

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [11]:
data1[ ~(data1 > 11) ]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
# Goal: Extract all even numbers
# % 2 == 0

data1 % 2 == 0

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False])

In [14]:
data1[ data1 % 2 == 0 ]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [16]:
data1 >= 2

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [17]:
data1 <= 10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [20]:
(data1 >= 2) & (data1 <= 10)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [21]:
#Extract all elements within range of 2 and 10

data1[ (data1 >= 2) & (data1 <= 10) ]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
# Extract all even numbers except 10

data1[ (data1 % 2 == 0) & (data1 != 10) ]

array([ 2,  4,  6,  8, 12, 14, 16, 18, 20, 22, 24])

In [23]:
data2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24])
data2 [ (data2 %2 ==0 ) & (data2 !=10)].reshape(5,5)

array([ 2,  4,  6,  8, 12, 14, 16, 18, 20, 22, 24])